deathban-time: 90 #This is in minutes.
deathban-message: "You have been deathbanned for %time% minutes." #Message shown to the player when they are deathbanned. %time% is replaced with the time the player is deathbanned for.
bypass-permission: "deathban.bypass" #Permission required to bypass deathban.
